-- MySQL Script generated by Garage
-- 07/31/17 19:58:57
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Table `Fluxo_caixa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Fluxo_caixa` (
  `janeiro` DECIMAL(10,2) NULL DEFAULT NULL,
  `fevereiro` DECIMAL(10,2) NULL DEFAULT NULL,
  `marco` DECIMAL(10,2) NULL DEFAULT NULL,
  `abril` DECIMAL(10,2) NULL DEFAULT NULL,
  `maio` DECIMAL(10,2) NULL DEFAULT NULL,
  `junho` DECIMAL(10,2) NULL DEFAULT NULL,
  `julho` DECIMAL(10,2) NULL DEFAULT NULL,
  `agosto` DECIMAL(10,2) NULL DEFAULT NULL,
  `setembro` DECIMAL(10,2) NULL DEFAULT NULL,
  `outubro` DECIMAL(10,2) NULL DEFAULT NULL,
  `novembro` DECIMAL(10,2) NULL DEFAULT NULL,
  `dezembro` DECIMAL(10,2) NULL DEFAULT NULL,
  `ano` VARCHAR(150) NULL DEFAULT NULL)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `cargos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cargos` (
  `pk_cargos` INT(11) NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `status` VARCHAR(10) NOT NULL,
  PRIMARY KEY (`pk_cargos`),
  UNIQUE INDEX `nome_UNIQUE` (`nome` ASC))
ENGINE = InnoDB
AUTO_INCREMENT = 11
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `clientes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `clientes` (
  `pk_cliente` INT(11) NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(50) NULL DEFAULT NULL,
  `cpf` VARCHAR(15) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `contato1` VARCHAR(15) NOT NULL,
  `contato` VARCHAR(15) NULL DEFAULT NULL,
  `status` VARCHAR(10) NULL DEFAULT NULL,
  UNIQUE INDEX `pk_clientes_UNIQUE` (`pk_cliente` ASC),
  UNIQUE INDEX `cpf_UNIQUE` (`cpf` ASC))
ENGINE = InnoDB
AUTO_INCREMENT = 13
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `clientes_enderecos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `clientes_enderecos` (
  `pk_clienteEndereco` INT(11) NOT NULL AUTO_INCREMENT,
  `logradouro` VARCHAR(45) NULL DEFAULT NULL,
  `bairro` VARCHAR(20) NULL DEFAULT NULL,
  `cidade` VARCHAR(30) NOT NULL,
  `estado` VARCHAR(4) NOT NULL,
  `pais` VARCHAR(20) NULL DEFAULT NULL,
  `cep` VARCHAR(11) NOT NULL,
  `fk_cliente` INT(11) NOT NULL,
  PRIMARY KEY (`pk_clienteEndereco`),
  UNIQUE INDEX `pk_clientesEnderecos_UNIQUE` (`pk_clienteEndereco` ASC),
  INDEX `fk_cliente_idx` (`fk_cliente` ASC),
  CONSTRAINT `fk_cliente_clie_endere`
    FOREIGN KEY (`fk_cliente`)
    REFERENCES `clientes` (`pk_cliente`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 8
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `fornecedores`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fornecedores` (
  `pk_fornecedor` INT(11) NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NULL DEFAULT NULL,
  `cpf` VARCHAR(15) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `contato1` VARCHAR(15) NOT NULL,
  `contato` VARCHAR(15) NULL DEFAULT NULL,
  `status` VARCHAR(10) NOT NULL,
  PRIMARY KEY (`pk_fornecedor`),
  UNIQUE INDEX `pk_clientes_UNIQUE` (`pk_fornecedor` ASC),
  UNIQUE INDEX `cpf_UNIQUE` (`cpf` ASC))
ENGINE = InnoDB
AUTO_INCREMENT = 10
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `funcionarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `funcionarios` (
  `pk_funcionario` INT(11) NOT NULL AUTO_INCREMENT,
  `fk_cargo` INT(11) NOT NULL,
  `nome` VARCHAR(45) NULL DEFAULT NULL,
  `cpf` VARCHAR(15) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `contato1` VARCHAR(15) NOT NULL,
  `contato` VARCHAR(15) NULL DEFAULT NULL,
  `status` VARCHAR(10) NULL DEFAULT NULL,
  `avatar` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`pk_funcionario`),
  UNIQUE INDEX `pk_clientes_UNIQUE` (`pk_funcionario` ASC),
  UNIQUE INDEX `cpf_UNIQUE` (`cpf` ASC),
  INDEX `fk_cargo_idx` (`fk_cargo` ASC),
  CONSTRAINT `fk_cargo_funcionario`
    FOREIGN KEY (`fk_cargo`)
    REFERENCES `cargos` (`pk_cargos`)
    ON UPDATE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 50
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `compras`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `compras` (
  `pk_compra` INT(11) NOT NULL AUTO_INCREMENT,
  `fk_fornecedor` INT(11) NOT NULL,
  `fk_funcionario` INT(11) NOT NULL,
  `datas` DATETIME NOT NULL,
  `numero` VARCHAR(45) NULL DEFAULT NULL,
  `status` VARCHAR(10) NOT NULL,
  `statusCompra` VARCHAR(15) NOT NULL,
  `usuarioInsert` VARCHAR(30) NULL DEFAULT NULL,
  `dataCriacao` DATETIME NULL DEFAULT NULL,
  `usuarioUpdate` VARCHAR(30) NULL DEFAULT NULL,
  `dataUpdate` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`pk_compra`),
  INDEX `fk_fornecedor_idx` (`fk_fornecedor` ASC),
  INDEX `fk_funcionario_compra_idx` (`fk_funcionario` ASC),
  CONSTRAINT `fk_fornecedor_compra`
    FOREIGN KEY (`fk_fornecedor`)
    REFERENCES `fornecedores` (`pk_fornecedor`)
    ON UPDATE CASCADE,
  CONSTRAINT `fk_funcionario_compra`
    FOREIGN KEY (`fk_funcionario`)
    REFERENCES `funcionarios` (`pk_funcionario`)
    ON UPDATE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 54
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `marcas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `marcas` (
  `pk_marca` INT(11) NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `status` VARCHAR(10) NOT NULL,
  PRIMARY KEY (`pk_marca`))
ENGINE = InnoDB
AUTO_INCREMENT = 33
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `modelos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `modelos` (
  `pk_modelo` INT(11) NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(50) NOT NULL,
  `status` VARCHAR(15) NOT NULL,
  PRIMARY KEY (`pk_modelo`))
ENGINE = InnoDB
AUTO_INCREMENT = 51
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `tipos_veiculos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tipos_veiculos` (
  `pk_tipo` INT(11) NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(50) NOT NULL,
  `status` VARCHAR(10) NOT NULL,
  PRIMARY KEY (`pk_tipo`))
ENGINE = InnoDB
AUTO_INCREMENT = 30
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `veiculos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `veiculos` (
  `pk_veiculo` INT(11) NOT NULL AUTO_INCREMENT,
  `fk_tipo` INT(11) NOT NULL,
  `placa` VARCHAR(11) NOT NULL,
  `fk_modelo` INT(11) NOT NULL,
  `fk_marca` INT(11) NOT NULL,
  `ano` YEAR(4) NOT NULL,
  `valor_compra` DECIMAL(10,2) NOT NULL,
  `valor_venda` DECIMAL(10,2) NOT NULL,
  `statusVeiculo` VARCHAR(15) NOT NULL,
  `status` VARCHAR(10) NOT NULL,
  PRIMARY KEY (`pk_veiculo`),
  UNIQUE INDEX `placa` (`placa` ASC),
  INDEX `fk_tipo_idx` (`fk_tipo` ASC),
  INDEX `fk_marca_idx` (`fk_marca` ASC),
  INDEX `fk_modelo_veiculo_idx` (`fk_modelo` ASC),
  CONSTRAINT `fk_marca_veiculo`
    FOREIGN KEY (`fk_marca`)
    REFERENCES `marcas` (`pk_marca`)
    ON UPDATE CASCADE,
  CONSTRAINT `fk_modelo_veiculo`
    FOREIGN KEY (`fk_modelo`)
    REFERENCES `modelos` (`pk_modelo`)
    ON UPDATE CASCADE,
  CONSTRAINT `fk_tipo_veiculo`
    FOREIGN KEY (`fk_tipo`)
    REFERENCES `tipos_veiculos` (`pk_tipo`)
    ON UPDATE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 35
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `compras_itens`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `compras_itens` (
  `pk_item` INT(11) NOT NULL AUTO_INCREMENT,
  `fk_compra` INT(11) NOT NULL,
  `fk_veiculo` INT(11) NOT NULL,
  `valor_compra` DECIMAL(10,2) NULL DEFAULT NULL,
  PRIMARY KEY (`pk_item`),
  INDEX `fk_compra_idx` (`fk_compra` ASC),
  INDEX `fk_veiculo_idx` (`fk_veiculo` ASC),
  CONSTRAINT `fk_compra_item`
    FOREIGN KEY (`fk_compra`)
    REFERENCES `compras` (`pk_compra`)
    ON UPDATE CASCADE,
  CONSTRAINT `fk_veiculo_item`
    FOREIGN KEY (`fk_veiculo`)
    REFERENCES `veiculos` (`pk_veiculo`)
    ON UPDATE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 52
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `financeiros_entradas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `financeiros_entradas` (
  `pk_entrada` INT(11) NOT NULL AUTO_INCREMENT,
  `fk_compra` INT(11) NULL DEFAULT NULL,
  `data_emissao` DATETIME NULL DEFAULT NULL,
  `data_vencimento` DATETIME NULL DEFAULT NULL,
  `data_baixa` DATETIME NULL DEFAULT NULL,
  `valor` DECIMAL(10,2) NULL DEFAULT NULL,
  `status` VARCHAR(10) NOT NULL,
  `usuarioCriacao` VARCHAR(50) NOT NULL,
  `dataCriacao` DATETIME NULL DEFAULT NULL,
  `usuarioUpdate` VARCHAR(50) NULL DEFAULT NULL,
  `dataUpdate` DATETIME NULL DEFAULT NULL,
  `statusFinanceiro` VARCHAR(20) NULL DEFAULT NULL,
  `descricao` VARCHAR(250) NULL DEFAULT NULL,
  `classificacao` VARCHAR(150) NULL DEFAULT NULL,
  PRIMARY KEY (`pk_entrada`))
ENGINE = InnoDB
AUTO_INCREMENT = 65
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `financeiros_saidas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `financeiros_saidas` (
  `pk_saida` INT(11) NOT NULL AUTO_INCREMENT,
  `fk_venda` INT(11) NOT NULL,
  `data_emissao` DATETIME NOT NULL,
  `data_vencimento` DATETIME NOT NULL,
  `data_baixa` DATETIME NULL DEFAULT NULL,
  `valor` DECIMAL(10,2) NOT NULL,
  `status` VARCHAR(10) NOT NULL,
  `usuarioCriacao` VARCHAR(50) NOT NULL,
  `dataCriacao` DATETIME NOT NULL,
  `usuarioUpdate` VARCHAR(50) NULL DEFAULT NULL,
  `dataUpdade` DATETIME NULL DEFAULT NULL,
  `statusFinanceiro` VARCHAR(20) NULL DEFAULT NULL,
  PRIMARY KEY (`pk_saida`))
ENGINE = InnoDB
AUTO_INCREMENT = 42
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `fornecedores_enderecos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fornecedores_enderecos` (
  `pk_clienteEndereco` INT(11) NOT NULL AUTO_INCREMENT,
  `logradouro` VARCHAR(45) NULL DEFAULT NULL,
  `bairro` VARCHAR(20) NULL DEFAULT NULL,
  `cidade` VARCHAR(30) NOT NULL,
  `estado` VARCHAR(4) NOT NULL,
  `pais` VARCHAR(20) NULL DEFAULT NULL,
  `cep` VARCHAR(11) NOT NULL,
  `fk_fornecedor` INT(11) NOT NULL,
  PRIMARY KEY (`pk_clienteEndereco`),
  UNIQUE INDEX `pk_clientesEnderecos_UNIQUE` (`pk_clienteEndereco` ASC),
  INDEX `fk_clientes_idx` (`fk_fornecedor` ASC),
  CONSTRAINT `fk_fornecedor_endereco`
    FOREIGN KEY (`fk_fornecedor`)
    REFERENCES `fornecedores` (`pk_fornecedor`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 8
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `funcionarios_enderecos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `funcionarios_enderecos` (
  `pk_clienteEndereco` INT(11) NOT NULL AUTO_INCREMENT,
  `logradouro` VARCHAR(45) NULL DEFAULT NULL,
  `bairro` VARCHAR(20) NULL DEFAULT NULL,
  `cidade` VARCHAR(30) NOT NULL,
  `estado` VARCHAR(4) NOT NULL,
  `pais` VARCHAR(20) NULL DEFAULT NULL,
  `cep` VARCHAR(11) NOT NULL,
  `fk_funcionario` INT(11) NOT NULL,
  PRIMARY KEY (`pk_clienteEndereco`),
  UNIQUE INDEX `pk_clientesEnderecos_UNIQUE` (`pk_clienteEndereco` ASC),
  INDEX `fk_funcionario_idx` (`fk_funcionario` ASC),
  CONSTRAINT `fk_funcionario_func_endere`
    FOREIGN KEY (`fk_funcionario`)
    REFERENCES `funcionarios` (`pk_funcionario`)
    ON UPDATE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 31
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `grupos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `grupos` (
  `pk_grupo` INT(11) NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NULL DEFAULT NULL,
  `descricao` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`pk_grupo`))
ENGINE = InnoDB
AUTO_INCREMENT = 12
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `modulos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `modulos` (
  `pk_modulo` INT(11) NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`pk_modulo`))
ENGINE = InnoDB
AUTO_INCREMENT = 26
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `tipos_reparos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tipos_reparos` (
  `pk_tipo` INT(11) NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(50) NOT NULL,
  `status` VARCHAR(10) NOT NULL,
  PRIMARY KEY (`pk_tipo`))
ENGINE = InnoDB
AUTO_INCREMENT = 30
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `reparos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `reparos` (
  `pk_reparo` INT(11) NOT NULL AUTO_INCREMENT,
  `fk_veiculo` INT(11) NOT NULL,
  `fk_tipos` INT(11) NOT NULL,
  `descricao` VARCHAR(255) NOT NULL,
  `valor` DECIMAL(10,2) NOT NULL,
  `status` VARCHAR(10) NOT NULL,
  `usuarioCriacao` VARCHAR(50) NOT NULL,
  `dataCriacao` DATETIME NOT NULL,
  `usuarioUpdate` VARCHAR(50) NULL DEFAULT NULL,
  `dataUpdate` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`pk_reparo`),
  INDEX `fk_reparo_idx` (`fk_tipos` ASC),
  INDEX `fk_veiculo_idx` (`fk_veiculo` ASC),
  CONSTRAINT `fk_tipo_reparo`
    FOREIGN KEY (`fk_tipos`)
    REFERENCES `tipos_reparos` (`pk_tipo`)
    ON UPDATE CASCADE,
  CONSTRAINT `fk_veiculo_reparo`
    FOREIGN KEY (`fk_veiculo`)
    REFERENCES `veiculos` (`pk_veiculo`)
    ON UPDATE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 31
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `vendas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `vendas` (
  `pk_venda` INT(11) NOT NULL AUTO_INCREMENT,
  `fk_clientes` INT(11) NOT NULL,
  `fk_funcionarios` INT(11) NOT NULL,
  `status` VARCHAR(10) NOT NULL,
  `statusVenda` VARCHAR(15) NOT NULL,
  `usuarioCriacao` VARCHAR(30) NULL DEFAULT NULL,
  `dataCriacao` DATETIME NOT NULL,
  `usuarioUpdate` VARCHAR(50) NULL DEFAULT NULL,
  `dataUpdate` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`pk_venda`),
  INDEX `fk_cliente_idx` (`fk_clientes` ASC),
  INDEX `fk_funcionario_idx` (`fk_funcionarios` ASC),
  CONSTRAINT `fk_clientes_venda`
    FOREIGN KEY (`fk_clientes`)
    REFERENCES `clientes` (`pk_cliente`)
    ON UPDATE CASCADE,
  CONSTRAINT `fk_funcionarios_venda`
    FOREIGN KEY (`fk_funcionarios`)
    REFERENCES `funcionarios` (`pk_funcionario`)
    ON UPDATE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 36
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `vendas_itens`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `vendas_itens` (
  `pk_item` INT(11) NOT NULL AUTO_INCREMENT,
  `fk_venda` INT(11) NOT NULL,
  `fk_veiculo` INT(11) NOT NULL,
  `valor_venda` DECIMAL(10,2) NULL DEFAULT NULL,
  PRIMARY KEY (`pk_item`),
  INDEX `fk_veiculo_idx` (`fk_veiculo` ASC),
  INDEX `fk_venda_idx` (`fk_venda` ASC),
  CONSTRAINT `fk_veiculo_ve_item`
    FOREIGN KEY (`fk_veiculo`)
    REFERENCES `veiculos` (`pk_veiculo`)
    ON UPDATE CASCADE,
  CONSTRAINT `fk_vendas_ve_item`
    FOREIGN KEY (`fk_venda`)
    REFERENCES `vendas` (`pk_venda`)
    ON UPDATE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 34
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
